"""Single machine-readable registry for fleet missions."""

from __future__ import annotations

RUNTIME_ADAPTERS = (
    "autonomous-fleet-adapter-orca",
    "autonomous-fleet-adapter-claude-code",
    "autonomous-fleet-adapter-grok",
    "autonomous-fleet-adapter-codex",
)

MISSIONS: dict[str, dict[str, object]] = {
    "doc-sync": {
        "shipped": True,
        "skill_dir": "doc-sync",
        "progress_doc": "doc-sync-progress.md",
        "readiness_doc": "doc-sync-readiness.md",
        "metrics": ("drift_open", "code_bug_findings"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "test-coverage": {
        "shipped": True,
        "skill_dir": "test-coverage",
        "progress_doc": "test-coverage-progress.md",
        "readiness_doc": "test-coverage-readiness.md",
        "metrics": ("gaps_open", "coverage_regressed"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "dependency-update": {
        "shipped": False,
        "skill_dir": "dependency-update",
        "progress_doc": "dependency-update-progress.md",
        "readiness_doc": "dependency-update-readiness.md",
        "metrics": ("advisories_open", "majors_deferred"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "cleanup": {
        "shipped": False,
        "skill_dir": "cleanup",
        "progress_doc": "cleanup-progress.md",
        "readiness_doc": "cleanup-readiness.md",
        "metrics": ("cleanup_items_open",),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "bug-batch": {
        "shipped": False,
        "skill_dir": "bug-batch",
        "progress_doc": "bug-batch-progress.md",
        "readiness_doc": "bug-batch-readiness.md",
        "metrics": ("bugs_open", "bugs_skipped"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "adversarial-review-and-fix": {
        "shipped": True,
        "skill_dir": "adversarial-review-and-fix",
        "progress_doc": "arch-build-progress.md",
        "readiness_doc": "arch-build-readiness.md",
        "metrics": ("p0_open", "p1_open", "findings_open", "ops_queue_count"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "targeted-migration": {
        "shipped": False,
        "skill_dir": "targeted-migration",
        "progress_doc": "migration-progress.md",
        "readiness_doc": "migration-readiness.md",
        "metrics": ("migration_items_open", "old_axis_removed"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "design-integration": {
        "shipped": False,
        "skill_dir": "design-integration",
        "progress_doc": "parity-progress.md",
        "readiness_doc": "parity-readiness.md",
        "metrics": ("parity_items_open", "regressions"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "landing-page-convergence": {
        "shipped": False,
        "archived": True,
        "skill_dir": "landing-page-convergence",
        "progress_doc": "landing-progress.md",
        "readiness_doc": "landing-readiness.md",
        "metrics": ("divergences_open",),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "legacy-rebuild": {
        "shipped": False,
        "archived": True,
        "skill_dir": "legacy-rebuild",
        "progress_doc": "rebuild-progress.md",
        "readiness_doc": "rebuild-readiness.md",
        "metrics": ("units_open", "floor_preserved", "e2e_verified"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "3",
    },
    "take-product-to-completion": {
        "shipped": False,
        "skill_dir": "take-product-to-completion",
        "progress_doc": "completion-progress.md",
        "readiness_doc": "completion-readiness.md",
        "metrics": ("in_items_open", "roadmap_count", "stubs_remaining", "e2e_verified"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "3",
    },
    "inference-cost": {
        "shipped": False,
        "skill_dir": "inference-cost",
        "progress_doc": "inference-cost-progress.md",
        "readiness_doc": "inference-cost-readiness.md",
        "metrics": ("cost_regressed", "quality_regressed", "levers_open"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "product-framing": {
        "shipped": False,
        "archived": True,
        "skill_dir": "product-framing",
        "progress_doc": "framing-progress.md",
        "readiness_doc": "framing-readiness.md",
        "metrics": ("spec_frozen", "open_questions"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "browser-qa-fix": {
        "shipped": False,
        "skill_dir": "browser-qa-fix",
        "progress_doc": "qa-progress.md",
        "readiness_doc": "qa-readiness.md",
        "metrics": ("health_before", "health_after"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "security-cso-audit": {
        "shipped": False,
        "archived": True,
        "skill_dir": "security-cso-audit",
        "progress_doc": "security-progress.md",
        "readiness_doc": "security-readiness.md",
        "metrics": (
            "findings_confirmed",
            "findings_closed",
            "findings_refuted",
            "audit_mode",
        ),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "devex-audit": {
        "shipped": False,
        "archived": True,
        "skill_dir": "devex-audit",
        "progress_doc": "devex-progress.md",
        "readiness_doc": "devex-readiness.md",
        "metrics": ("dx_score", "doc_gaps_open"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "release-document": {
        "shipped": False,
        "archived": True,
        "skill_dir": "release-document",
        "progress_doc": "release-doc-progress.md",
        "readiness_doc": "release-doc-readiness.md",
        "metrics": ("doc_gaps_closed", "deploy_verified"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "incident-investigate": {
        "shipped": False,
        "skill_dir": "incident-investigate",
        "progress_doc": "incident-progress.md",
        "readiness_doc": "incident-readiness.md",
        "metrics": ("rca_confirmed", "regression_tests_added"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    # Exploratory handoff-to-product triad (on-disk SKILL trees; not yet shipped).
    "scaffold-align": {
        "shipped": False,
        "skill_dir": "scaffold-align",
        "progress_doc": "scaffold-align-progress.md",
        "readiness_doc": "scaffold-align-readiness.md",
        "metrics": ("align_items_open", "check_green", "seam_frozen", "scaffold_ok"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "contract-first-build": {
        "shipped": False,
        "skill_dir": "contract-first-build",
        "progress_doc": "contract-build-progress.md",
        "readiness_doc": "contract-build-readiness.md",
        "metrics": ("in_items_open", "roadmap_count", "stubs_remaining", "ops_queue_count"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "3",
    },
    "agents-layer": {
        "shipped": False,
        "skill_dir": "agents-layer",
        "progress_doc": "agents-layer-progress.md",
        "readiness_doc": "agents-layer-readiness.md",
        "metrics": (
            "migration_items_open",
            "seam_unwired_open",
            "old_axis_removed",
            "evals_passing",
            "deploy_pending_ops",
        ),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "3",
    },
}
