"""Single machine-readable registry for fleet missions."""

from __future__ import annotations

RUNTIME_ADAPTERS = (
    "autonomous-fleet-adapter-orca",
    "autonomous-fleet-adapter-claude-code",
    "autonomous-fleet-adapter-grok",
    "autonomous-fleet-adapter-codex",
)

MISSIONS: dict[str, dict[str, object]] = {
    "doc-sync": {
        "shipped": True,
        "skill_dir": "doc-sync",
        "progress_doc": "doc-sync-progress.md",
        "readiness_doc": "doc-sync-readiness.md",
        "metrics": ("drift_open", "code_bug_findings"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "test-coverage": {
        "shipped": True,
        "skill_dir": "test-coverage",
        "progress_doc": "test-coverage-progress.md",
        "readiness_doc": "test-coverage-readiness.md",
        "metrics": ("gaps_open", "coverage_regressed"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "dependency-update": {
        "shipped": False,
        "skill_dir": "dependency-update",
        "progress_doc": "dependency-update-progress.md",
        "readiness_doc": "dependency-update-readiness.md",
        "metrics": ("advisories_open", "majors_deferred"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "cleanup": {
        "shipped": False,
        "skill_dir": "cleanup",
        "progress_doc": "cleanup-progress.md",
        "readiness_doc": "cleanup-readiness.md",
        "metrics": ("cleanup_items_open",),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "1",
    },
    "bug-batch": {
        "shipped": False,
        "skill_dir": "bug-batch",
        "progress_doc": "bug-batch-progress.md",
        "readiness_doc": "bug-batch-readiness.md",
        "metrics": ("bugs_open", "bugs_skipped"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "adversarial-review-and-fix": {
        "shipped": True,
        "skill_dir": "adversarial-review-and-fix",
        "progress_doc": "arch-build-progress.md",
        "readiness_doc": "arch-build-readiness.md",
        "metrics": ("p0_open", "p1_open", "findings_open", "ops_queue_count"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "targeted-migration": {
        "shipped": False,
        "skill_dir": "targeted-migration",
        "progress_doc": "migration-progress.md",
        "readiness_doc": "migration-readiness.md",
        "metrics": ("migration_items_open", "old_axis_removed"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "design-integration": {
        "shipped": False,
        "skill_dir": "design-integration",
        "progress_doc": "parity-progress.md",
        "readiness_doc": "parity-readiness.md",
        "metrics": ("parity_items_open", "regressions"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "landing-page-convergence": {
        "shipped": False,
        "skill_dir": "landing-page-convergence",
        "progress_doc": "landing-progress.md",
        "readiness_doc": "landing-readiness.md",
        "metrics": ("divergences_open",),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
    "legacy-rebuild": {
        "shipped": False,
        "skill_dir": "legacy-rebuild",
        "progress_doc": "rebuild-progress.md",
        "readiness_doc": "rebuild-readiness.md",
        "metrics": ("units_open", "floor_preserved", "e2e_verified"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "3",
    },
    "take-product-to-completion": {
        "shipped": False,
        "skill_dir": "take-product-to-completion",
        "progress_doc": "completion-progress.md",
        "readiness_doc": "completion-readiness.md",
        "metrics": ("in_items_open", "roadmap_count", "stubs_remaining", "e2e_verified"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "3",
    },
    "inference-cost": {
        "shipped": False,
        "skill_dir": "inference-cost",
        "progress_doc": "inference-cost-progress.md",
        "readiness_doc": "inference-cost-readiness.md",
        "metrics": ("cost_regressed", "quality_regressed", "levers_open"),
        "adapters_required": RUNTIME_ADAPTERS,
        "tier": "2",
    },
}
